### PR TITLE
Attributes in Swift don't need a leading `@`

### PR DESCRIPTION
**Pull request by marcinwyszynski**
This change fixes the whole getters/setters business. Courtesy of codebeat.co ;)

### CODE REVIEW

**Comment by alykhank** [comment]
Can you clarify what you're referring to in terms of getters and setters, please?

Also, according to [The Swift Programming Language (Swift 2.2): Attributes](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Attributes.html#//apple_ref/doc/uid/TP40014097-CH35-ID347), the `@` is not optional. Changing this in our `Swift.g4` file has caused several files in the functional tests to be parsed incorrectly, and trigger inconsistent warnings. Can you please explain the rationale for making it optional?

**Comment by marcinwyszynski** [comment]
Sure. For example, `subscriptDeclaration` is defined like this:

```antlr
subscriptDeclaration
 : subscriptHead subscriptResult getterSetterBlock
 | subscriptHead subscriptResult getterSetterKeywordBlock
 | subscriptHead subscriptResult codeBlock
 ;
```

Let's say we have code that looks like this (from Swift standard library):

```swift
public subscript(i: Int) -> Element {
  get {
    return getElement(i, wasNativeTypeChecked: _isNativeTypeChecked)
  }
   
  nonmutating set {
    if _fastPath(_isNative) {
      _native[i] = newValue
    }
    else {
      var refCopy = self
      refCopy.replace(
        subRange: i...i, with: 1, elementsOf: CollectionOfOne(newValue))
    }
  }
}
```

We would expect it to be matched by the first rule, but it's instead matched by the third (most general) one with `get` and `set` interpreted as closures. This is because in the `getterSetterBlock`, `setterClause` is defined like this:

```antlr
setterClause : attributes? 'set' setterName? codeBlock ;
```

Because `nonmutating` does is not an `attribute` (does not have a leading `@`) ANTLR ends up matching the block with a fallback definition.

Coming to think of it one could alternatively add `declarationModifiers?` to the `setterClause`.

**Comment by marcinwyszynski** [comment]
OK mate, PTAL.

**Comment by alykhank** [comment]
Thanks @marcinwyszynski, this looks much better! A few things are still missing (most of which are explained in [CONTRIBUTING.md](https://github.com/sleekbyte/tailor/blob/master/.github/CONTRIBUTING.md)):

- [ ] Grammar tests to demonstrate a case that supports the need for the change (you could add the Swift snippet above to `src/test/swift/com/sleekbyte/tailor/grammar/ClassesAndStructures.swift`)
- [ ] Comment in the grammar to indicate that there is a discrepancy from [The Swift Language Reference](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/zzSummaryOfTheGrammar.html#//apple_ref/doc/uid/TP40014097-CH38-ID458) (e.g. `// declarationModifiers missing in the Swift Language Reference`)
- [ ] An issue to track this PR and a reference in the description indicating that it is resolved (i.e. "Resolves #XYZ."), please also mention it at the beginning of the title

Lastly, please rebase your branch on top of the latest version of master so that we can approve and merge! 😄

**Comment by marcinwyszynski** [comment]
Sorry mate, I have no bandwidth to jump through your hoops. Feel free to
take over and commit as you see fit, I don't care one bit about authorship.

On Monday 25 April 2016, Alykhan Kanji <notifications@github.com> wrote:

> Thanks @marcinwyszynski <https://github.com/marcinwyszynski>, this looks
> much better! A few things are still missing (most of which are explained in
> CONTRIBUTING.md
> <https://github.com/sleekbyte/tailor/blob/master/.github/CONTRIBUTING.md>
> ):
>
>    - Grammar tests to demonstrate a case that supports the need for the
>    change (you could add the Swift snippet above to
>    src/test/swift/com/sleekbyte/tailor/grammar/ClassesAndStructures.swift)
>    - Comment in the grammar to indicate that there is a discrepancy from The
>    Swift Language Reference
>    <https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/zzSummaryOfTheGrammar.html#//apple_ref/doc/uid/TP40014097-CH38-ID458>
>    (e.g. // declarationModifiers missing in the Swift Language Reference)
>    - An issue to track this PR and a reference in the description
>    indicating that it is resolved (i.e. "Resolves #XYZ."), please also mention
>    it at the beginning of the title
>
> Lastly, please rebase your branch on top of the latest version of master
> so that we can approve and merge! 😄
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sleekbyte/tailor/pull/362#issuecomment-214515088>
>


-- 
Marcin

**Comment by alykhank** [comment]
Sure, we'll take it from here.

**Pull request closed without merging**
